### PR TITLE
Improve Verification

### LINKED ISSUE #44: Trust Individuals
During set up there's a a part where it pops random people's (gnu keys? some sort of key?) on screen and asks if you trust them. How do I know if I can trust these people?

### LINKED ISSUE #128: Launch Bitcoin-Qt before importing Descriptors
**Is your feature request related to a problem? Please describe.**
No visual progress is displayed during import descriptors although rescanning the blockchain for transactions is a potentially slow operation.

**Describe the solution you'd like**
Stop bitcoind and start bitcoin-qt before importing descriptors in bails-wallet

**Describe alternatives you've considered**
Running bitcoin-qt the entire time bails-wallet is running. This provides an opportunity for distraction and consumes more resources making the GUI potentially laggy.

### PR DESCRIPTION
**Pull request by BenWestgate**
Closes #44
Closes #128

### CODE REVIEW

**Comment by BenWestgate** [comment]
Closes #138 .

**Comment by BenWestgate** [comment]
@epiccurious: this is fully tested, passing CI and ready for your brief code review. I suggest skimming it so you're familiar with how much the code has changed in this branch  so you can find everything later.

**Review by BenWestgate — COMMENTED** [review]
I have read all the changes and they look good to me.

**Review by epiccurious — APPROVED** [review]

**Comment by epiccurious** [comment]
ACK ba5c8943c43d3b697acf56e01ac0394d768e96b0

**Pull request merged**
